### ISSUE TITLE
Cannot read property 'push' of undefined 오류

### ISSUE THREAD

**Issue by closers-seulbi** [teamatus/openNAMU#12]
위키에서 문서 편집을 한 뒤, "수정 내용 저장하기" 를 누르면
아래와 같은 오류가 발생합니다.

`Cannot read property 'push' of undefined`
`TypeError: Cannot read property 'push' of undefined`
`    at /var/www/nodejs/kerbalkorea_cf-ssl/routes/index.js:94:37`
`    at Layer.handle [as handle_request] (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/layer.js:95:5)`
`    at next (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/route.js:131:13)`
`    at Route.dispatch (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/route.js:112:3)`
`    at Layer.handle [as handle_request] (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/layer.js:95:5)`
`    at /var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/index.js:277:22`
`    at param (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/index.js:349:14)`
`    at param (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/index.js:365:14)`
`    at Function.process_params (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/index.js:410:3)`
`    at next (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/router/index.js:271:10)`

위키 주소: https://wiki.kerbalkorea.cf

**Comment by 2DU** [comment]
대문은 Admin만 편집되게 설정 되어 있어 그런듯 합니다.

wiki.json 에서 "canEdit" 이 true로 설정되어 있는지 확인해 주십시오.

**Comment by closers-seulbi** [comment]
@2DU 
대문의 canEdit 은 true 로 설정되어 있습니다.
다른 문서는 문제 없이 편집이 되는데, 대문만 그러는거 같네요;;

**Comment by closers-seulbi** [comment]
자동으로 작성되는 Hello World, Node.js 등의 페이지들은 편집이 가능하나, 새로 작성되는 문서들 (대문이라던가 json 수정해서 직접 넣은 페이지라던가) 은 편집이 불가능합니다.

**Comment by closers-seulbi** [comment]
> Error: Can't set headers after they are sent.
>     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
>     at ServerResponse.header (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/response.js:718:10)
>     at ServerResponse.send (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/response.js:163:12)
>     at done (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/response.js:957:10)
>     at Object.exports.renderFile (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/pug/lib/index.js:405:12)
>     at View.exports.__express [as engine] (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/pug/lib/index.js:448:11)
>     at View.render (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/view.js:126:8)
>     at tryRender (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/application.js:639:10)
>     at EventEmitter.render (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/application.js:591:3)
>     at ServerResponse.render (/var/www/nodejs/kerbalkorea_cf-ssl/node_modules/express/lib/response.js:961:7)

**Comment by 2DU** [comment]
밤에 여러 패치를 해보았는데 최신 버전을 적용해도 같은 오류가 발생하나요?

**Comment by closers-seulbi** [comment]
한번 시도해 보겠습니다!

**Comment by closers-seulbi** [comment]
@2DU 네, 여전히 오류를 뿜어내네요 ;;

**Comment by 2DU** [comment]
이런 내부 개발자에게 물어야겠네요...

**Comment by 2DU** [comment]
노드 버전이 어찌 되십니까?

**Comment by closers-seulbi** [comment]
@2DU 위에 적혀있는 대로
node v6.3.1
npm v3.10.3
입니다

**Comment by closers-seulbi** [comment]
노드 버전 낮춰보겠습니다 :)

**Comment by 2DU** [comment]
파이팅 :]

**Comment by closers-seulbi** [comment]
@2DU 노드 버전을 4.2.6 으로 내렸습니다만, 똑같은 오류를 뿜어내네요.. ;;
아무래도 스크립트 문제 인것처럼 보여요 ...

이제부터라도 저도 node.js 개발방법 알아놔야 겠네요

**Comment by 2DU** [comment]
이런 근데 백 엔드 제작자가 괌으로 떠났답니다 ㅜ

( 리눅스 파일 접근 권한이 혹시 잘못된 건 아닐까요 예를 들면 777이 아니라 그냥 소유자만 편집으로 되 있다던지

**Comment by closers-seulbi** [comment]
문제가 될 지는 모르겠지만, 모든 파일 777로 맞춰놓고 실행해 봐야겠네요

**Comment by zlzleking** [comment]
wiki.json만 777로 하시면 됩니다. 우선 그 전에 소유자를 본인으로 만드는 게 먼저겠지만요.

**Comment by closers-seulbi** [comment]
@zlzleking 시도해보겠습니다 :+1:

**Comment by 2DU** [comment]
해결 됬나요?
